name: Upload Lido Report to Dune Analytics

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          python-version: '3.11'

      - name: Create .env file from GitHub secrets / vars
        run: |
          echo "RPC_URL=${{ secrets.RPC_URL }}" >> .env
          echo "HASH_CONSENSUS_ADDRESS=${{ vars.HASH_CONSENSUS_ADDRESS }}" >> .env
          echo "LIDO_ADDRESS=${{ vars.LIDO_ADDRESS }}" >> .env
          echo "ACCOUNTING_ORACLE_ADDRESS=${{ vars.ACCOUNTING_ORACLE_ADDRESS }}" >> .env
          echo "WITHDRAWAL_VAULT_ADDRESS=${{ vars.WITHDRAWAL_VAULT_ADDRESS }}" >> .env
          echo "EL_REWARDS_VAULT_ADDRESS=${{ vars.EL_REWARDS_VAULT_ADDRESS }}" >> .env
          echo "BURNER_ADDRESS=${{ vars.BURNER_ADDRESS }}" >> .env
          echo "DUNE_API_KEY=${{ secrets.DUNE_API_KEY }}" >> .env

      - name: Install dependencies
        # Using bash -l {0} ensures conda is initialized properly within the shell.
        shell: bash -l {0}
        run: |
          conda install -y -c conda-forge pandas requests python-dotenv
          # For dune-client (PyPI only):
          pip install dune-client

      - name: Install Node Dependencies
        run: npm install

      - name: Generate Lido Report
        run: npm run report

      - name: Upload to Dune Analytics
        shell: bash -l {0}
        run: python scripts/upload_to_dune.py 